export const LOAD_TRENDING_GIFS = {
  INIT: "LOAD_TRENDING_GIFS_INIT",
  SUCCESS: "LOAD_TRENDING_GIFS_SUCESS",
  FAILURE: "LOAD_TRENDING_GIFS_FAILURE",
};
export const SEARCH = {
  INIT: "SEARCH_INIT",
  SUCCESS: "SEARCH_SUCCESS",
  FAILURE: "SEARCH_FAILURE",
};

export const PAGE_INCREMENT = "PAGE_INCREMENT";
