export const LOAD_GIFS = {
  INIT: "LOAD_GIFS_INIT",
  SUCCESS: "LOAD_GIFS_SUCESS",
  FAILURE: "LOAD_GIFS_FAILURE",
};

export const SEARCH = {
  INIT: "SEARCH_INIT",
  SUCCESS: "SEARCH_SUCCESS",
  FAILURE: "SEARCH_FAILURE",
};

export const RESET = "GIFY_RESET";
export const SET_SEARCH_PAGE = "SET_SEARCH_PAGE";
export const SET_TRENDING_PAGE = "SET_TRENDING_PAGE";
export const SET_TERM = "SET_TERM";
export const PAGE_INCREMENT = "PAGE_INCREMENT";
